apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

metadata:
  name: my-app
  namespace: app
spec:
  interval: 1m
  path: "./apps/app"
  prune: true
  targetNamespace: app
  sourceRef:
    kind: GitRepository
    name: flux-system